name: NetEase Cloud Game Auto Sign

on:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间16点(北京时间24点)运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run sign script
        env:
          CG_ACCOUNT: ${{ secrets.CG_ACCOUNT }}
          CG_PASSWORD: ${{ secrets.CG_PASSWORD }}
        run: python sign.py
